import type { CoverState } from '../types/cover';

export const BRAND_COLORS = {
  primaryBlue: '#146AFF',
  lightBlue: '#CBDDFF',
  accentYellow: '#F5A623',
  darkText: '#183444',
  white: '#FFFFFF',
} as const;

export const STORAGE_KEY = 'mediagen_pro_state';

export const DEFAULT_STATE: CoverState = {
  appMode: 'instagram',
  postFormat: 'news',
  coverFontPreset: 'instagram',
  title: 'THE FUTURE OF\nVENTURE CAPITAL',
  category: 'SaaS Trends',
  image: null,
  imageFocusX: 50,
  imageFocusY: 50,
  imageZoom: 100,
  isGradient: true,
  gradientPreset: 'brand',
  ratio: 'vertical',
  imageOrientation: 'vertical',
  layoutMode: 'overlay',
  template: 'bold',
  overlayOpacity: 0.6,
  titleColor: '#FFFFFF',
  categoryColor: '#F5A623',
  bgColor: '#146AFF',
  caption: 'stanbase.tech',
  captionColor: '#FFFFFF',
  photoCredit: '',
  photoCreditCorner: 'br',
  showSafeZones: false,
  textTransform: 'uppercase',
  useGlassmorphism: false,
  contentAlignment: 'flex-end',
  glassBlur: 25,
  glassWidth: 'full',
  logos: [],
  logoSize: 100,
  logoOpacity: 100,
  logoTint: 'original',
  eventTitleAlign: 'left',
  eventMeta: '',
  eventSpeakers: [],
};
